<?php

namespace Database\Seeders;

use App\Models\Theme;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ThemeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $themes = [
            [
                'name' => 'Default Light',
                'slug' => 'default-light',
                'description' => 'Clean and modern light theme',
                'is_default' => true,
                'is_active' => true,
                'colors' => [
                    'primary' => '#3B82F6',
                    'secondary' => '#64748B',
                    'success' => '#10B981',
                    'danger' => '#EF4444',
                    'warning' => '#F59E0B',
                    'info' => '#0EA5E9',
                    'light' => '#F8FAFC',
                    'dark' => '#1E293B',
                    'background' => '#FFFFFF',
                    'text' => '#0F172A',
                ],
            ],
            [
                'name' => 'Default Dark',
                'slug' => 'default-dark',
                'description' => 'Sleek dark theme for reduced eye strain',
                'is_default' => false,
                'is_active' => true,
                'colors' => [
                    'primary' => '#60A5FA',
                    'secondary' => '#94A3B8',
                    'success' => '#34D399',
                    'danger' => '#F87171',
                    'warning' => '#FBBF24',
                    'info' => '#38BDF8',
                    'light' => '#334155',
                    'dark' => '#0F172A',
                    'background' => '#1E293B',
                    'text' => '#F1F5F9',
                ],
            ],
            [
                'name' => 'Blue Ocean',
                'slug' => 'blue-ocean',
                'description' => 'Calm and professional blue theme',
                'is_default' => false,
                'is_active' => true,
                'colors' => [
                    'primary' => '#0284C7',
                    'secondary' => '#0369A1',
                    'success' => '#059669',
                    'danger' => '#DC2626',
                    'warning' => '#D97706',
                    'info' => '#0891B2',
                    'light' => '#E0F2FE',
                    'dark' => '#075985',
                    'background' => '#FFFFFF',
                    'text' => '#0C4A6E',
                ],
            ],
            [
                'name' => 'Purple Dream',
                'slug' => 'purple-dream',
                'description' => 'Creative purple theme',
                'is_default' => false,
                'is_active' => true,
                'colors' => [
                    'primary' => '#9333EA',
                    'secondary' => '#7C3AED',
                    'success' => '#10B981',
                    'danger' => '#EF4444',
                    'warning' => '#F59E0B',
                    'info' => '#8B5CF6',
                    'light' => '#FAF5FF',
                    'dark' => '#581C87',
                    'background' => '#FFFFFF',
                    'text' => '#3B0764',
                ],
            ],
            [
                'name' => 'Green Nature',
                'slug' => 'green-nature',
                'description' => 'Fresh and natural green theme',
                'is_default' => false,
                'is_active' => true,
                'colors' => [
                    'primary' => '#16A34A',
                    'secondary' => '#15803D',
                    'success' => '#22C55E',
                    'danger' => '#DC2626',
                    'warning' => '#F59E0B',
                    'info' => '#0EA5E9',
                    'light' => '#F0FDF4',
                    'dark' => '#14532D',
                    'background' => '#FFFFFF',
                    'text' => '#052E16',
                ],
            ],
            [
                'name' => 'Orange Sunset',
                'slug' => 'orange-sunset',
                'description' => 'Warm and energetic orange theme',
                'is_default' => false,
                'is_active' => true,
                'colors' => [
                    'primary' => '#EA580C',
                    'secondary' => '#C2410C',
                    'success' => '#10B981',
                    'danger' => '#DC2626',
                    'warning' => '#F59E0B',
                    'info' => '#0EA5E9',
                    'light' => '#FFF7ED',
                    'dark' => '#7C2D12',
                    'background' => '#FFFFFF',
                    'text' => '#431407',
                ],
            ],
            [
                'name' => 'Red Fire',
                'slug' => 'red-fire',
                'description' => 'Bold and powerful red theme',
                'is_default' => false,
                'is_active' => true,
                'colors' => [
                    'primary' => '#DC2626',
                    'secondary' => '#B91C1C',
                    'success' => '#10B981',
                    'danger' => '#EF4444',
                    'warning' => '#F59E0B',
                    'info' => '#0EA5E9',
                    'light' => '#FEF2F2',
                    'dark' => '#7F1D1D',
                    'background' => '#FFFFFF',
                    'text' => '#450A0A',
                ],
            ],
            [
                'name' => 'Gray Professional',
                'slug' => 'gray-professional',
                'description' => 'Neutral and professional gray theme',
                'is_default' => false,
                'is_active' => true,
                'colors' => [
                    'primary' => '#475569',
                    'secondary' => '#334155',
                    'success' => '#10B981',
                    'danger' => '#EF4444',
                    'warning' => '#F59E0B',
                    'info' => '#0EA5E9',
                    'light' => '#F8FAFC',
                    'dark' => '#0F172A',
                    'background' => '#FFFFFF',
                    'text' => '#020617',
                ],
            ],
            [
                'name' => 'Teal Modern',
                'slug' => 'teal-modern',
                'description' => 'Modern and stylish teal theme',
                'is_default' => false,
                'is_active' => true,
                'colors' => [
                    'primary' => '#0D9488',
                    'secondary' => '#0F766E',
                    'success' => '#10B981',
                    'danger' => '#EF4444',
                    'warning' => '#F59E0B',
                    'info' => '#06B6D4',
                    'light' => '#F0FDFA',
                    'dark' => '#134E4A',
                    'background' => '#FFFFFF',
                    'text' => '#042F2E',
                ],
            ],
            [
                'name' => 'Pink Soft',
                'slug' => 'pink-soft',
                'description' => 'Gentle and elegant pink theme',
                'is_default' => false,
                'is_active' => true,
                'colors' => [
                    'primary' => '#EC4899',
                    'secondary' => '#DB2777',
                    'success' => '#10B981',
                    'danger' => '#EF4444',
                    'warning' => '#F59E0B',
                    'info' => '#0EA5E9',
                    'light' => '#FDF2F8',
                    'dark' => '#831843',
                    'background' => '#FFFFFF',
                    'text' => '#500724',
                ],
            ],
            [
                'name' => 'High Contrast',
                'slug' => 'high-contrast',
                'description' => 'High contrast theme for accessibility',
                'is_default' => false,
                'is_active' => true,
                'colors' => [
                    'primary' => '#000000',
                    'secondary' => '#1F2937',
                    'success' => '#059669',
                    'danger' => '#DC2626',
                    'warning' => '#D97706',
                    'info' => '#0369A1',
                    'light' => '#FFFFFF',
                    'dark' => '#000000',
                    'background' => '#FFFFFF',
                    'text' => '#000000',
                ],
            ],
            [
                'name' => 'Custom',
                'slug' => 'custom',
                'description' => 'Customizable theme',
                'is_default' => false,
                'is_active' => true,
                'colors' => [
                    'primary' => '#3B82F6',
                    'secondary' => '#64748B',
                    'success' => '#10B981',
                    'danger' => '#EF4444',
                    'warning' => '#F59E0B',
                    'info' => '#0EA5E9',
                    'light' => '#F8FAFC',
                    'dark' => '#1E293B',
                    'background' => '#FFFFFF',
                    'text' => '#0F172A',
                ],
            ],
        ];

        foreach ($themes as $theme) {
            Theme::create($theme);
        }
    }
}